### ISSUE TITLE
Docker example

### ISSUE THREAD

**Issue by soullivaneuh** [sveltejs/sapper-template#175]
It would be great to have a docker ready example with all the configuration we have to do.

Currently, I'm stuck with the live-reload port:

```
Firefox can’t establish a connection to the server at http://localhost:10000/__sapper__
```

So I have to bind the port:

```
services:
  app:
    ports:
      - 3000
      - '10000:10000'
    volumes:
      - ${PWD}:/app
```

But it's not ideal, especially when you work with multiple projects.

Or a how to documentation like that ? https://github.com/brunch/auto-reload-brunch/tree/2.7.1#client-side-settings

Currently, I don't even know if I can configure this.
